app = 'ix-tips-predictions'
primary_region = 'jnb'
console_command = '/code/manage.py shell'

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = 'sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py createcachetable"'

[env]
  TZ = 'Africa/Nairobi'

[processes]
  app  = 'gunicorn --bind 0.0.0.0:8080 --workers 1 --timeout 120 --preload score_predictor.wsgi'
  cron = 'supercronic /code/crontab'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  processes = ['cron']

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'
